#
#  ____       _   _            _   _
# |  _ \     | | | |          | \ | |
# | |_) | ___| |_| |_ ___ _ __|  \| | __ ___   __
# |  _ < / _ \ __| __/ _ \ '__| . ` |/ _` \ \ / /
# | |_) |  __/ |_| ||  __/ |  | |\  | (_| |\ V /
# |____/ \___|\__|\__\___|_|  |_| \_|\__,_| \_/
#
# BetterNavigating V${project.version}

# Enabling public or private location savings
privateWayPoints : {privateWayPoints}

# Maximum Waypoints per folder
maximumWaypoints : {maximumWaypoints}

# Displaying welcome message
welcomeMessage : {welcomeMessage}

# BossBar Navigating style
BossBar : {BossBar}

# BossBar coloring: possible colors are: blue, green, pink, white, purple, red, yellow
# More information can be found over here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
BossBar_color: {BossBar_color}

# Distance to waypoint before ending navigation
Distance : {Distance}

# Whether or not animations are enabled
enableAnimations : {enableAnimations}

# language: implemented languages are "dutch", "english", "german","french" & "spanish"
# delete your messages.yml file and reload the plugin to change the language file
# More information can be found over here: https://github.com/ThomasVerschoor/BetterNav/tree/main/src/main/resources/lang
language : {language}

# check for height
height_check: {height_check}

# automatically save your deathlocations
death_location_save: {death_location_save}

# start navigation to deathlocation on death
death_nav: {death_nav}





